from .AlignAverageWidget import AlignAverageWidget
from .AlignmentLineWidget import AlignmentLineWidget
from .AlignXYWidget import AlignXYWidget
from .ArduinoWidget import ArduinoWidget
from .AutofocusWidget import AutofocusWidget
from .basewidgets import WidgetFactory
from .BeadRecWidget import BeadRecWidget
from .ConsoleWidget import ConsoleWidget
from .EtSTEDWidget import EtSTEDWidget
from .FFTWidget import FFTWidget
from .FocusLockWidget import FocusLockWidget
from .ImageWidget import ImageWidget
from .LaserWidget import LaserWidget
from .MotCorrWidget import MotCorrWidget
from .PositionerWidget import PositionerWidget
from .RecordingWidget import RecordingWidget
from .SLMWidget import SLMWidget
from .ScanWidgetBase import ScanWidgetBase
from .ScanWidgetMoNaLISA import ScanWidgetMoNaLISA
from .ScanWidgetPointScan import ScanWidgetPointScan
from .RotationScanWidget import RotationScanWidget
from .RotatorWidget import RotatorWidget
from .SettingsWidget import SettingsWidget
from .SLMWidget import SLMWidget
from .TilingWidget import TilingWidget
from .ULensesWidget import ULensesWidget
from .ViewWidget import ViewWidget
from .WatcherWidget import WatcherWidget
#from .SetupStatusWidget import SetupStatusWidget # KDC 101 widget
from .KDC101stageWidget import KDC101stageWidget # KDC 101 widget
from .ZAlignmentWidget import ZAlignmentWidget